name: Deploy to Azure Static Website

on:
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Login to Azure
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Upload to Azure Storage
      uses: azure/cli@v1
      with:
        inlineScript: |
         az account set --subscription "1f9e870a-8f55-4a59-9977-55f5a592c78b"
          az storage blob upload-batch \
            --auth-mode login \
            --account-name kmreshtml \
            --destination '$web' \
            --source "." \
            --overwrite
