name: Deploy to Azure Static Website

on:
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Login to Azure
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Upload to Azure Storage
      uses: azure/cli@v1
      with:
        inlineScript: |
         az account set --subscription "1f9e870a-8f55-4a59-9977-55f5a592c78b"
         for file in $(find . -type f \( -name "*.html" -o -name "*.css" \)); do
          rel_path="${file#./}"
          echo "Uploading $rel_path"
          az storage blob upload \
            --auth-mode login \
            --account-name kmreshtml \
            --container-name '$web' \
            --file "$file" \
            --name "$rel_path" \
            --content-cache-control "no-cache" \
            --overwrite
          done
    - name: Purge Azure CDN Cache
      uses: azure/cli@v1
      with:
        inlineScript: |
          az account set --subscription "1f9e870a-8f55-4a59-9977-55f5a592c78b"
          az cdn endpoint purge \
            --resource-group kmres01 \
            --profile-name resumeCDN \
            --name resume \
            --content-paths '/*'